add_newline = false

format = """
$directory\
$git_branch\
$jobs\
$character\
"""

[directory]
format = "[$path]($style) "
style = "#A6DBFF"
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
style = "#dfd1fb"

[character]
disabled = false
success_symbol = '[❯](bold blue)'

[jobs]
symbol = ''
style = 'bold red'
