add_newline = false

format = """
$directory\
$git_branch\
$jobs\
$character\
"""

[directory]
format = "[$path]($style) "
style = "dimmed"
truncation_symbol = '…/'
truncate_to_repo = false

[git_branch]
format = "[$branch]($style) "
style = "dimmed red"

[character]
disabled = false
success_symbol = '[❯](bold blue)'

[jobs]
symbol = ''
style = 'bold red'
